In [117]:
# -*- coding: utf-8 -*-
import sys
import pandas as pd
import numpy as np
from numpy import *
df=pd.read_csv('traindata_ccy.csv',encoding = "gb18030")

In [118]:
df.head()

Unnamed: 0                  学生ID     生源省市  性别  民族  政治面貌.群众  政治面貌.团员  \
0           0  6520905ee393ca7c7dc7  宁夏回族自治区   1   1        0        1   
1           1  c5f7d43ab8328c3108c6      北京市   0   1        0        1   
2           2  78a1a12f2ba616373b7b  广西壮族自治区   1   1        0        1   
3           3  67349330bfce350d0444      北京市   1   1        0        1   
4           4  dfcdedc8922db1978f09      重庆市   1   0        0        1   

   政治面貌.预备党员  裸眼视力(左)  裸眼视力(右)   ...     大类.定向招生  大类.筑梦 大类.特长生      高三排名  \
0          0      4.8      5.0   ...           0      1      0  0.002817   
1          0      0.5      0.5   ...           0      0      0  0.446154   
2          0      NaN      NaN   ...           0      0      0  0.016129   
3          0      4.4      4.4   ...           0      0      0  0.016556   
4          0      4.5      4.6   ...           0      0      0  0.002315   

       成绩方差  专利数      社会活动       获奖数  竞赛成绩    综合GPA  
0 -0.262115  0.0  0.028571  0.000000   0.0  3.57018  
1  1.960142  0.0  0.028571  0.076923   0.0  3.47444  
2 -0.252413  0.0  0.057143  0.128205   0.0  3.63056  
3 -0.203312  0.0  0.057143  0.128205   0.0  3.81983  
4 -0.149474  0.0  0.000000  0.000000   0.0  2.69939  

[5 rows x 38 columns]

In [119]:
prov=zeros ((3023,3))

In [120]:
for i in range(0,3022):
    if df.loc[i,"生源省市".decode('utf8')]==u"河南省":
        prov[i,0]=1
    elif  df.loc[i,"生源省市".decode('utf8')]==u"河北省" :
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"山西省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"江西省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"青海省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"甘肃省":
        prov[i,0]=1    
    elif df.loc[i,"生源省市".decode('utf8')]==u"西藏自治区":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"贵州省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"内蒙古自治区":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"新疆维吾尔自治区":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"宁夏回族自治区":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"吉林省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"黑龙江省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"云南省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"辽宁省":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"广西壮族自治区":
        prov[i,0]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"四川省":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"广东省":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"重庆市":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"安徽省":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"福建省":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"江苏省":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"浙江省":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"北京市":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"天津市":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"上海市":
        prov[i,1]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"山东省":
        prov[i,2]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"陕西省":
        prov[i,2]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"海南省":
        prov[i,2]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"湖北省":
        prov[i,2]=1
    elif df.loc[i,"生源省市".decode('utf8')]==u"湖南省":
        prov[i,2]=1

In [121]:
print prov[0:100]
    

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1. 

In [122]:
for i in range(0,3022):
    if df.loc[i,"裸眼视力(左)".decode('utf8')]>0 and df.loc[i,"裸眼视力(左)".decode('utf8')]< 1.6:
        if df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.1:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.12:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.1
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.15:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.2
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.2:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.3
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.25:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.4
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.3:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.5
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.4:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.6
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.5:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.7
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.6:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.8
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.7:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.9
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.8:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=4.9
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 0.9:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=5.0
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 1.0:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=5.0
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 1.1:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=5.1
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 1.2:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=5.1
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 1.3:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=5.2
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 1.4:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=5.2
        elif df.loc[i,"裸眼视力(左)".decode('utf8')] == 1.5:
            df.loc[i,"裸眼视力(左)".decode('utf8')]=5.3
    
    if df.loc[i,"裸眼视力(右)".decode('utf8')]>0 and df.loc[i,"裸眼视力(右)".decode('utf8')]< 1.6:
        if df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.1:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.12:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.1
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.15:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.2
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.2:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.3
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.25:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.4
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.3:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.5
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.4:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.6
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.5:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.7
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.6:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.8
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.7:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.9
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.8:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=4.9
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 0.9:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=5.0
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 1.0:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=5.0
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 1.1:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=5.1
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 1.2:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=5.1
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 1.3:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=5.2
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 1.4:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=5.2
        elif df.loc[i,"裸眼视力(右)".decode('utf8')] == 1.5:
            df.loc[i,"裸眼视力(右)".decode('utf8')]=5.3

In [123]:
cla=zeros((3023,2))

In [124]:
for i in range(0,3022):
    if  df.loc[i,"考生类型".decode('utf8')] == u"农村应届":
        cla[i,1]=1
    elif  df.loc[i,"考生类型".decode('utf8')] == u"城镇应届":
        cla[i,0]=1
        cla[i,1]=1
    elif  df.loc[i,"考生类型".decode('utf8')] == u"城镇往届":
        cla[i,0]=1

        

In [125]:
df.insert(3,u"全国卷",prov[:,0])
df.insert(4,u"自主命题",prov[:,1])
df.insert(5,u"半自主命题",prov[:,2])

In [126]:
df.head()

Unnamed: 0                  学生ID     生源省市  全国卷  自主命题  半自主命题  性别  民族  \
0           0  6520905ee393ca7c7dc7  宁夏回族自治区  1.0   0.0    0.0   1   1   
1           1  c5f7d43ab8328c3108c6      北京市  0.0   1.0    0.0   0   1   
2           2  78a1a12f2ba616373b7b  广西壮族自治区  1.0   0.0    0.0   1   1   
3           3  67349330bfce350d0444      北京市  0.0   1.0    0.0   1   1   
4           4  dfcdedc8922db1978f09      重庆市  0.0   1.0    0.0   1   0   

   政治面貌.群众  政治面貌.团员   ...     大类.定向招生  大类.筑梦  大类.特长生      高三排名      成绩方差  专利数  \
0        0        1   ...           0      1       0  0.002817 -0.262115  0.0   
1        0        1   ...           0      0       0  0.446154  1.960142  0.0   
2        0        1   ...           0      0       0  0.016129 -0.252413  0.0   
3        0        1   ...           0      0       0  0.016556 -0.203312  0.0   
4        0        1   ...           0      0       0  0.002315 -0.149474  0.0   

       社会活动       获奖数  竞赛成绩    综合GPA  
0  0.028571  0.000000   0.0  3.57018  
1  0.028571  0.076923   0.0  3.47444  
2  0.057143  0.128205   0.0  3.63056  
3  0.057143  0.128205   0.0  3.81983  
4  0.000000  0.000000   0.0  2.69939  

[5 rows x 41 columns]

In [127]:
del df[u"生源省市"]

In [128]:
df.head()

Unnamed: 0                  学生ID  全国卷  自主命题  半自主命题  性别  民族  政治面貌.群众  \
0           0  6520905ee393ca7c7dc7  1.0   0.0    0.0   1   1        0   
1           1  c5f7d43ab8328c3108c6  0.0   1.0    0.0   0   1        0   
2           2  78a1a12f2ba616373b7b  1.0   0.0    0.0   1   1        0   
3           3  67349330bfce350d0444  0.0   1.0    0.0   1   1        0   
4           4  dfcdedc8922db1978f09  0.0   1.0    0.0   1   0        0   

   政治面貌.团员  政治面貌.预备党员   ...     大类.定向招生  大类.筑梦  大类.特长生      高三排名      成绩方差  \
0        1          0   ...           0      1       0  0.002817 -0.262115   
1        1          0   ...           0      0       0  0.446154  1.960142   
2        1          0   ...           0      0       0  0.016129 -0.252413   
3        1          0   ...           0      0       0  0.016556 -0.203312   
4        1          0   ...           0      0       0  0.002315 -0.149474   

   专利数      社会活动       获奖数  竞赛成绩    综合GPA  
0  0.0  0.028571  0.000000   0.0  3.57018  
1  0.0  0.028571  0.076923   0.0  3.47444  
2  0.0  0.057143  0.128205   0.0  3.63056  
3  0.0  0.057143  0.128205   0.0  3.81983  
4  0.0  0.000000  0.000000   0.0  2.69939  

[5 rows x 40 columns]

In [131]:
df.insert(14,u"城镇考生",cla[:,0])

ValueError: cannot insert 城镇考生, already exists

In [132]:
df.insert(15,u"应届考生",cla[:,1])

In [134]:
del df[u"考生类型"]

In [135]:
df.columns

Index([ u'Unnamed: 0',        u'学生ID',         u'全国卷',        u'自主命题',
             u'半自主命题',          u'性别',          u'民族',     u'政治面貌.群众',
           u'政治面貌.团员',   u'政治面貌.预备党员',     u'裸眼视力(左)',     u'裸眼视力(右)',
                u'身高',          u'体重',        u'城镇考生',        u'应届考生',
              u'外语语种',     u'学科类型.理工',     u'学科类型.文史',   u'学科类型.文理综合',
                u'年份',          u'成绩',      u'学部.理学部',  u'学部.经济与管理学部',
           u'学部.人文学部',   u'学部.社会科学学部', u'学部.信息与工程科学部',        u'优惠加分',
                u'大类',       u'大类.普通',       u'大类.自招',     u'大类.定向招生',
             u'大类.筑梦',      u'大类.特长生',        u'高三排名',        u'成绩方差',
               u'专利数',        u'社会活动',         u'获奖数',        u'竞赛成绩',
             u'综合GPA'],
      dtype='object')

In [138]:
df.to_csv("traindata_mxj.csv",encoding="gb18030")